export const CartActionTypes={
    ADD_TO_CART:"ADD_TO_CART",
    SUB_QTY:"SUB_QTY",
    ADD_QTY: "ADD_QTY",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    EMPTY_CART:"EMPTY_CART"
}


export const FilterActionTypes={
    ADD_COLOR:"ADD_COLOR",
    REMOVE_COLOR:"REMOVE_COLOR",
    RESET_COLORS:"RESET_COLORS",
    
    ADD_BRAND:"ADD_BRAND",
    REMOVE_BRAND:"REMOVE_BRAND",
    RESET_COLORS:"RESET_BRANDS",

    ADD_MATERIAL:"ADD_MATERIALS",
    REMOVE_MATERIAL:"REMOVE_MATERIAL",
    RESET_MATERIALS:"RESET_MATERIALS",

    SET_PRICE_RANG:"SET_PRICE_RANGE",
    RESET_PRICE_RANGE:"RESET_PRICE_RANGE",

    SET_SORTING:"SET_SORTING",
    RESET_SORTING:"RESET_SORTING",
    RESET_FILTER:"RESET_FILTER"
}